### ISSUE TITLE
  Pre-transform error: Failed to resolve import; when running project

### ISSUE THREAD

**Issue by neko-sukuriputo** [primefaces/primevue-examples#7]
![image](https://github.com/primefaces/primevue-examples/assets/51826615/59f6bedb-de9f-493d-a3e9-21441168fdc0)

Get Error Pre-transform error: Failed to resolve import when running example project in https://github.com/primefaces/primevue-examples/tree/main/nuxt-unstyled-tailwind

Reproduce Step:

`pnpm i`
`pnpm run dev`

**Comment by ljgazzano** [comment]
same error, working in Windows + VSCode.

**Comment by ibrim-asanov** [comment]
I got the same one and it's probably Windows related.

You can fix it by updating the **importPT** to:

`importPT: { as: 'Lara', from: '/presets/lara' }`

**Comment by ljgazzano** [comment]
I was found an dirty solution:

const presetpath = path.resolve(__dirname, "presets", "lara");
const presetpathDoubleSlashes = presetpath.replace(/\\/g, "//");

The error is only valid in Windows environment develop

**Comment by mikekidder** [comment]
Know this is closed, but the true fix is to let **path.resolve** do its thing:  pass it a string array.

   `     importPT: { from: path.resolve(__dirname, 'presets', 'lara') }`
   
It will figure out to use '/'  or '\' based on the OS - Window vs Linux.
